/*
Level: Intermediate SQL
Concepts: GROUP BY + HAVING, Subqueries, Conditional filters, Percent Contribution, Customer behavior analysis
Objective: Translate business rules into SQL logic and insights
Dataset: sales_dataset
*/

/*11. Find the highest and lowest sales values in the dataset.*/
select max(SALES) as Highest_sales, min(SALES) as Lowest_sales
from sales_dataset;

/*12. Count the number of unique customers.*/
select count(distinct CUSTOMERNAME) as Customers
from sales_dataset;
 
 /*13. Show sales performance by deal size category.*/
 select DEALSIZE, round(sum(SALES),2) as sales
 from sales_dataset
 group by DEALSIZE;
 
 /*14. Find which country generated the highest total sales.*/
 select ADDRESS, round(sum(SALES),2) as Highest_total_sales
 from sales_dataset
 group by ADDRESS
 order by Highest_total_sales desc
 limit 1;
 
 /*15. List all orders that have status “Cancelled”.*/
 select *
 from sales_dataset
 where STATUS='Cancelled';
 
 /*16. Show the average quantity ordered for each product code.*/
 select PRODUCTCODE, round(avg(QUANTITYORDERED),2) as Average
 from sales_dataset
 group by PRODUCTCODE;
 
 /*17. Display all orders placed in December*/
 select *
 from sales_dataset
 where MONTH_ID=12;
 
 /*18. Identify customers who ordered more than one product line.*/
 select CUSTOMERNAME, count(distinct PRODUCTLINE) as Count
 from sales_dataset
 group by CUSTOMERNAME
 having count(distinct PRODUCTLINE)>1;
 
/*19. Find the top 3 countries with the highest number of orders.*/
select ADDRESS, count(distinct ORDERNUMBER) as Highest_orders
from sales_dataset
group by ADDRESS
order by Highest_orders desc limit 3;

/*20. Find the total revenue generated by each country and display only countries with revenue above the overall average revenue.*/
select ADDRESS, round(sum(SALES),2) as Total_Revenue
from sales_dataset
group by ADDRESS
having sum(SALES)>(select avg(Address_Total)
				   from (select ADDRESS, sum(SALES) as Address_Total
						 from sales_dataset
						 group by ADDRESS) as t);

/*21. Find the total number of orders placed each year, sorted from most to least.*/
select YEAR_ID as Year, count(distinct ORDERNUMBER) as Total_orders
from sales_dataset
group by YEAR_ID
order by Total_orders desc;

/*22. Identify which product line has the highest average order quantity.*/
select PRODUCTLINE, round(avg(QUANTITYORDERED),2) as Highest_average
from sales_dataset
group by PRODUCTLINE
order by Highest_average desc limit 1;

/*23. Show the top 5 product codes by total revenue generated.*/
select PRODUCTCODE, round(sum(SALES),2) as Total_revenue
from sales_dataset
group by PRODUCTCODE
order by Total_revenue desc limit 5;

/*24. List all customers who placed orders in more than 3 different months.*/
select CUSTOMERNAME
from sales_dataset
group by CUSTOMERNAME
having count(distinct MONTH_ID)>3;

/*25. Calculate the percentage contribution of each product line to overall revenue.*/
select PRODUCTLINE, round(sum(SALES)*100.0/(select sum(SALES) from sales_dataset),2) as Percentage_Contributed
from sales_dataset
group by PRODUCTLINE;

/*26. Display the number of cancelled orders for each product line.*/
select PRODUCTLINE, count(distinct ORDERNUMBER) as cancelled_orders
from sales_dataset
where STATUS='Cancelled'
group by PRODUCTLINE;

/*27. Find the total revenue generated from “Large” deal size orders.*/
select DEALSIZE, sum(SALES) as Total_revenue
from sales_dataset
where DEALSIZE like '%Large%'
group by DEALSIZE;

/*28. Show the address with the lowest number of unique customers.*/
select address, count(distinct CUSTOMERNAME) as unique_customers
from sales_dataset
group by address
order by unique_customers asc limit 1;

/*29. Identify the top 3 months with the highest total sales across all years.*/
select monthname(ORDERDATE) as Month, round(sum(SALES),2) as Highest_sales
from sales_dataset
group by monthname(ORDERDATE)
order by Highest_sales desc limit 3;

/*30. For each customer, calculate the average sales amount per order and list only customers whose average is above the overall dataset average.*/
select CUSTOMERNAME, round(avg(SALES),2) as Average_sales 
from sales_dataset
group by CUSTOMERNAME
having avg(SALES)>(select avg(SALES) from sales_dataset);
